version: "3.8"

services:
  # --- DB Service --- 
  db:
    image: pgvector/pgvector:pg16
    container_name: anime_db
    restart: always 
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-anime_password}
      POSTGRES_DB: ${POSTGRES_DB:-anime_finder}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # --- Object Storage Service --- 
  minio:
    image: minio/minio:latest
    container_name: anime_minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minioadmin}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
volumes:
  postgres_data:
  minio_data: